nginx-ingress:
  rbac:
    create: true 
  controller:
    ingressClass: nginx-jee-test
    replicaCount: 1
    metrics:
      enabled: true
    service:
      nodePorts:
        http: 32080
      type: NodePort
    stats:
      enabled: true
    image:
      #    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.19.0
  defaultBackend:
    replicaCount: 1 
      

tomcat:
  replicaCount: 5
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-jee-test
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      # kubernetes.io/tls-acme: "true"
    path: /k8s-jee-test
    #hosts:
    #- "localhost"
  extraEnv:
  - name: TEST_APP_PARAM
    value: "dunno"
  service:
    name: http
    #nodePorts:
    #  http: 32079
    type: NodePort 
    # externalPort: 80
    # internalPort: 8080

